#ifndef APPLICATION_DELEGATE_H
#define APPLICATION_DELEGATE_H

typedef struct ApplicationDelegate APPLICATION_DELEGATE;

typedef void(*APPLICATION_RETRIEVE_LIST)(APPLICATION_DELEGATE*);
typedef void(*APPLICATION_LAUNCH)(APPLICATION_DELEGATE*, int);

struct ApplicationDelegate
{
	APPLICATION_RETRIEVE_LIST retrieveList;
	APPLICATION_LAUNCH launch;
};

#endif
